# Generated by Django 4.2.5 on 2024-11-04 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocajachica',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localtime),
        ),
    ]
