# Generated by Django 4.2.5 on 2024-12-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0002_alter_movimientocajachica_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldodiariocajachica',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saldodiariocajachica',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='saldodiariocajachica',
            table='saldo_diario_caja',
        ),
    ]
