# Generated by Django 4.2.5 on 2023-09-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='documento',
            new_name='documento',
        ),
    ]
