# Generated by Django 4.2.5 on 2023-10-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='observacion',
            name='especialidad',
            field=models.TextField(blank=True, help_text='Nombre de la especialidad donde el/la paciente consulta', null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='procedimientos',
            field=models.TextField(blank=True, help_text='Tipo de procedimiento o actividad que se realizó en la consulta', null=True, verbose_name='Procedimiento'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='tratamientos',
            field=models.TextField(blank=True, help_text='Prescripciones médicas farmacológicas y no farmacológicas ', null=True, verbose_name='Tratamiento'),
        ),
    ]
