# Generated by Django 4.2.5 on 2023-10-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_remove_observacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('F', 'Fisioterapia'), ('P', 'Psicologia'), ('G', 'Ginecologia')], default='F', help_text='Nombre de la especialidad donde el/la paciente consulta', verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='procedimientos',
            field=models.TextField(blank=True, help_text='Tipo de procedimiento o actividad que se realizó en la consulta', max_length=200, null=True, verbose_name='Procedimiento'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='tratamientos',
            field=models.TextField(blank=True, help_text='Prescripciones médicas farmacológicas y no farmacológicas ', max_length=200, null=True, verbose_name='Tratamiento'),
        ),
    ]
