# Generated by Django 4.2.5 on 2023-10-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alter_observacion_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Fisioterapia', 'Fisioterapia'), ('Psicologia', 'Psicologia'), ('Ginecologia', 'Ginecologia')], default='F', help_text='Nombre de la especialidad donde el/la paciente consulta', verbose_name='Especialidad'),
        ),
    ]
