# Generated by Django 4.2.5 on 2024-09-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_turno_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Fisioterapia', 'Fisioterapia'), ('Psicologia', 'Psicologia'), ('Ginecologia', 'Ginecologia')], default='Fisioterapia', help_text='Nombre de la especialidad donde el/la paciente consulta', max_length=50, verbose_name='Especialidad'),
        ),
    ]
