# Generated by Django 5.1.1 on 2024-11-26 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_alter_observacion_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiempoAgendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agendamiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de agendamiento')),
                ('duracion_agendamiento', models.FloatField(verbose_name='Duración de agendamiento')),
            ],
        ),
    ]
