# Generated by Django 5.1.1 on 2024-11-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_tiempoagendamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempoagendamiento',
            name='turno',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pacientes.turno', verbose_name='Turno '),
            preserve_default=False,
        ),
    ]
