# Generated by Django 5.1.1 on 2024-11-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_remove_turno_fecha_turno_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='unique_turno_fecha_hora_medico',
        ),
    ]
