# Generated by Django 4.2.5 on 2024-10-13 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la categoría')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('salario_diario', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario diario')),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total de bonificaciones')),
                ('deducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total de deducciones')),
                ('fecha_contratacion', models.DateField(verbose_name='Fecha de contratación')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='Fecha de terminación')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado actual del empleado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarios.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoSalario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('salario_total', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Salario total')),
                ('empleados', models.ManyToManyField(to='salarios.empleado', verbose_name='Empleados')),
            ],
            options={
                'verbose_name': 'Pago de salario',
                'verbose_name_plural': 'Pagos de salarios',
            },
        ),
    ]
