# Generated by Django 4.2.5 on 2024-10-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagosalario',
            options={'ordering': ['created_at'], 'verbose_name': 'salario', 'verbose_name_plural': 'salarios'},
        ),
        migrations.AlterModelTable(
            name='pagosalario',
            table='salario',
        ),
    ]
