# Generated by Django 4.2.5 on 2024-10-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarios', '0002_alter_pagosalario_options_alter_pagosalario_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='salario_diario',
            new_name='salario_base',
        ),
    ]
