# Generated by Django 4.2.5 on 2024-10-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarios', '0003_rename_salario_diario_empleado_salario_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.CharField(default=12323, max_length=11, unique=True, verbose_name='documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarios.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Salario base'),
        ),
    ]
