# Generated by Django 4.2.5 on 2024-10-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('M', 'Medico'), ('S', 'Secretaria'), ('G', 'Gerencia'), ('A', 'Administracion'), ('V', 'Venta'), ('T', 'Taller')], default='S', max_length=1, verbose_name='Sector'),
        ),
    ]
