# Generated by Django 5.1.1 on 2024-11-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=250, verbose_name='Razon social')),
                ('ruc', models.CharField(max_length=9, verbose_name='RUC')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono o celular')),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('tipo', models.CharField(choices=[('C', 'Cliente'), ('P', 'Proveedor'), ('A', 'Ambos')], default='C', max_length=1, verbose_name='Tipo de entidad (Cliente, Proveedor, Ambos)')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado actual de la factura')),
            ],
        ),
    ]
