# Generated by Django 5.1.1 on 2024-11-03 22:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoFactura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('nombre_objeto', models.CharField(max_length=250, unique=True, verbose_name='NombreProducto')),
                ('codigo_objeto', models.CharField(blank=True, max_length=250, null=True, verbose_name='Codigo Producto')),
                ('precio_objeto', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio del producto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
