# Generated by Django 5.1.1 on 2024-11-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_objetofactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetofactura',
            name='estado_objeto',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado actual del objeto'),
        ),
    ]
