# Generated by Django 5.1.1 on 2024-11-17 16:55

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_objetofactura_estado_objeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('timbrado', models.CharField(max_length=20, verbose_name='Timbrado')),
                ('validez_timbrado', models.DateField(default=datetime.datetime(2023, 12, 12, 0, 0))),
                ('cliente_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='factura.proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
