# Generated by Django 5.1.1 on 2024-11-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='objeto_factura',
            field=models.ManyToManyField(related_name='factura_objeto', to='factura.objetofactura'),
        ),
    ]
