# Generated by Django 5.1.1 on 2024-11-18 01:30

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_factura_objeto_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='validez_timbrado',
            new_name='inicio_validez_timbrado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='objeto_factura',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_factura_opciones',
            field=models.CharField(choices=[('V', 'Vigente'), ('C', 'Cancelada'), ('A', 'Anulada'), ('P', 'Pendiente'), ('R', 'Rechazada')], default='P', max_length=1, verbose_name='Estado actual de la factura : Vigente, Cancelada, Anulada, Pendiente, Rechazada'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fin_validez_timbrado',
            field=models.DateField(default=datetime.datetime(2025, 10, 23, 0, 0)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='timbrado',
            field=models.CharField(default='123456789', max_length=20, verbose_name='Timbrado'),
        ),
    ]
