# Generated by Django 5.1.1 on 2024-11-18 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_detallefactura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallefactura',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='factura.factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='objeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='factura.objetofactura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Precio del producto'),
        ),
    ]
